module Stats exposing (names)

names : List String
names =
  [ "Acidity"
  , "Adventure"
  , "Aerodynamics"
  , "Affection"
  , "Attention Span"
  , "Beepiness"
  , "Bookishness"
  , "Buoyancy"
  , "Caprice"
  , "Charm"
  , "Clumsiness"
  , "Curiosity"
  , "Daydreaming"
  , "Difficulty"
  , "Entrepreneurship"
  , "Fashion"
  , "Favorite Number"
  , "Friendship"
  , "Gender"
  , "Grace"
  , "Guts"
  , "Honesty"
  , "Humor"
  , "Imagination"
  , "Insubordination"
  , "Jitteriness"
  , "Laziness"
  , "Magic"
  , "Mischief"
  , "Moé"
  , "Mystery"
  , "Naïveté"
  , "Optimism"
  , "Patience"
  , "Pep"
  , "Persistence"
  , "Playfulness"
  , "Puns"
  , "Rhyme"
  , "Shyness"
  , "Sleepiness"
  , "Special Defense"
  , "Speed"
  , "Spice Tolerance"
  , "Spoiledness"
  , "Spunk"
  , "Squishiness"
  , "Stress"
  , "Tenderness"
  , "Valor"
  , "Viscosity"
  , "Whimsy"
  , "Wisdom"
  ]
