module Stats exposing (names)

names : List String
names =
  [ "Acceleration"
  , "Acidity"
  , "Adventure"
  , "Aerodynamics"
  , "Affection"
  , "Albedo"
  , "Ambition"
  , "Anxiety"
  , "Appetite"
  , "Armor Class"
  , "Attention Span"
  , "Beepiness"
  , "Bookishness"
  , "Bounce"
  , "Buoyancy"
  , "Buyer Satisfaction"
  , "Caprice"
  , "Charm"
  , "Clumsiness"
  , "Controller Ports"
  , "Coolness"
  , "Curiosity"
  , "Cushiony"
  , "Daydreaming"
  , "Density"
  , "Difficulty"
  , "Draw Distance"
  , "Durability"
  , "Edginess"
  , "Elasticity"
  , "Entrepreneurship"
  , "Erdős Number"
  , "Eye Sparkle"
  , "Fashion"
  , "Favorite Number"
  , "Fire Resistance"
  , "Forgetfulness"
  , "Friendship"
  , "Gender"
  , "Good Vibes"
  , "Grace"
  , "Grip Strength"
  , "Guts"
  , "Haughtiness"
  , "Hit Dice"
  , "Honesty"
  , "Humor"
  , "Imagination"
  , "Independence"
  , "Insubordination"
  , "Jitteriness"
  , "Jumpiness"
  , "Laziness"
  , "Leadership"
  , "Loudness"
  , "Luck"
  , "Magic"
  , "Malleability"
  , "Melancholy"
  , "Mischief"
  , "Moé"
  , "Mystery"
  , "Naïveté"
  , "Nonchalance"
  , "Optimism"
  , "Patience"
  , "Pep"
  , "Persistence"
  , "Playfulness"
  , "Processor Speed"
  , "Puns"
  , "Rarity"
  , "Rhyme"
  , "Serenity"
  , "Shader Quality"
  , "Shyness"
  , "Sincerity"
  , "Sleepiness"
  , "Slipperiness"
  , "Solubility"
  , "Special Defense"
  , "Spice Tolerance"
  , "Spoiledness"
  , "Spunk"
  , "Squishiness"
  , "Stickiness"
  , "Storage Capacity"
  , "Stress"
  , "Swimming"
  , "Temperature"
  , "Teleport Control"
  , "Tenderness"
  , "Texture Detail"
  , "Top Speed"
  , "Trustworthiness"
  , "Tsundere-ness"
  , "Valor"
  , "Vigor"
  , "Viscosity"
  , "Whimsy"
  , "Wisdom"
  , "Wittiness"
  , "Wordiness"
  , "XP Level"
  , "Zeal"
  ]
